using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace POSModel.Models	
{
	public class CompanySettings
	{
		public int CompanySettingID { get; set; }
		public decimal SalesTax { get; set; }
		public int CountryID { get; set; }
		public string TimeZone { get; set; }
		public decimal MinCommission { get; set; }
		public decimal MaxCommission { get; set; }
		public decimal RepairCommission { get; set; }
		public int InvoiceStartNumber { get; set; }
		public decimal DefaultJobDownPayment { get; set; }
		public decimal CustomerRefAmount { get; set; }
		public decimal EmployeeRefAmount { get; set; }
		public decimal OrgSalesmanSplitAmount { get; set; }
		public int CompanyID { get; set; }
		public int AvailableTextMessages { get; set; }
		public int POStartNumber { get; set; }
		public bool ShowQuantityInCustomerQuote { get; set; }
		public bool ShowUnitPriceInCustomerQuote { get; set; }
		public bool SendCustomerReminders { get; set; }
		public bool SendContractorReminders { get; set; }
		public string EmailDisplayName { get; set; }
		public bool AutomaticEmailToNewUsers { get; set; }
		public int DefaultJobCompletionChecklistID { get; set; }
		public bool SalesmanTextMessageEnabled { get; set; }
		public bool ShowPaymentMethodInPaymentNotification { get; set; }
		public bool ShowPaymentMethodInViewInvoice { get; set; }
		public bool ShowPaymentMethodInCompletionCertificate { get; set; }
		public int GridItemsPerPage { get; set; }
		public bool ShowSummaryTotals { get; set; }
		public bool SendInvoiceEmailToCustomerOnQuoteApproved { get; set; }
		public bool SendInvoiceTextMessageToCustomerOnQuoteApproved { get; set; }
		public int CalculateMarginPercentBasedOn { get; set; }
		public bool ShowInStorePaymentMethodViewInvoice { get; set; }
		public bool ShowQuantityInQuote { get; set; }
		public bool ShowUnitPriceInQuote { get; set; }
		public bool ShowItemNameInQuote { get; set; }
		public bool ShowAmountInQuote { get; set; }
		public bool ShowQuantityInInvoice { get; set; }
		public bool ShowUnitPriceInInvoice { get; set; }
		public bool ShowItemNameInInvoice { get; set; }
		public bool ShowAmountInInvoice { get; set; }
		public bool ShowUOMInQuote { get; set; }
		public bool ShowUOMInInvoice { get; set; }
		public bool ShowPaymentMethodInInvoice { get; set; }
		public bool ShowServiceTypeInQuote { get; set; }
		public bool ShowServiceTypeInInvoice { get; set; }
		public int TaxType { get; set; }
		public bool SalesTaxAsCost { get; set; }
		public string DefaultTaxText { get; set; }
		public bool ShowLaborFeesInJobDetails { get; set; }
		public decimal FloatBag { get; set; }
		public bool LockInvoiceWorkOrder { get; set; }
		public bool UseSalesmanEmail { get; set; }
		public string ETransferEmailPhone { get; set; }
		public bool ShowLaborUnitCostInJobDetails { get; set; }
		public bool SetLaborTax { get; set; }
		public bool ChargeCardFeesInViewInvoice { get; set; }
		public string SalesRepLabel { get; set; }
		public bool SetAutoTax { get; set; }
		public bool TaxCalculationAfterDiscount { get; set; }
		public string CustomerLabel { get; set; }
		public string QuoteLabel { get; set; }
		public string InvoiceLabel { get; set; }
		public bool ShowContractInQuote { get; set; }
		public bool ShowCreditCardPaymentMethodViewInvoice { get; set; }
		public bool ShowCashPaymentMethodViewInvoice { get; set; }
		public bool ShowCheckPaymentMethodViewInvoice { get; set; }
		public decimal? CalcMarginBeforeTax { get; set; }
		public string CustomReplyToEmail { get; set; }
		public bool AddExpensesToQISummarySection { get; set; }
		public string Layout { get; set; }
		public bool ShowSubtotalEachServiceTypeInQuote { get; set; }
		public int ShowProductsByCategory { get; set; }
		public int QuoteExpirationDays { get; set; }
		public bool RightToRecission { get; set; }
		public bool ShowVendorName { get; set; }
		public decimal? SubTotalOverheadPercentage { get; set; }
		public bool? ApplyOverheadToSubTotal { get; set; }
		public decimal MaterialOverheadPercentage { get; set; }
		public bool? ApplyMaterialOverheadToSellPrice { get; set; }
		public decimal LaborOverheadPercentage { get; set; }
		public bool? ApplyLaborOverheadToSellPrice { get; set; }
		public string GSTNo { get; set; }
		public string ProductIncomeAccount { get; set; }
		public string ProductExpenseAccount { get; set; }
		public bool ShowOutOfStock { get; set; }
		public bool RestrictInvoiceReset { get; set; }
		public string GSTTaxRateName { get; set; }
		public string ExemptTaxRateName { get; set; }
		public int PaymentTermID { get; set; }
		public string DefaultMessageForQuote { get; set; }
		public string DefaultMessageForInvoice { get; set; }
		public int ShowSqYdInQuoteInvoice { get; set; }
		public bool DisplayPaymentTermInViewInvoice { get; set; }
		public bool DisplaySalesmanNameInViewInvoice { get; set; }
		public bool DisplaySalesmanPhoneInViewInvoice { get; set; }
		public bool DisplayInvoiceDateInViewInvoice { get; set; }
		public bool DisplaySalesmanEmailInViewInvoice { get; set; }
		public string DiscountAccount { get; set; }
		public string ShippingCostAccount { get; set; }
		public string ContractorPaymentExpenseAccount { get; set; }
		public string VendorBillPaymentExpenseAccount { get; set; }
		public string LaborServiceExpenseAccount { get; set; }
		public string VendorBillPaymentRebateAccount { get; set; }
		public string LaborServiceIncomeAccount { get; set; }
		public string VendorBillExpenseAccount { get; set; }
		public string ReferralExpenseAccount { get; set; }
		public string VendorCreditAccount { get; set; }
		public string SalesmanPaymentExpenseAccount { get; set; }
		public string TaxesAndLicensesAccount { get; set; }
		public string VendorPSTExpenseAccount { get; set; }
		public string OtherExpenseAccount { get; set; }
		public string CreditCardFeesExpenseAccount { get; set; }
		public string CreditCardFeesIncomeAccount { get; set; }
		public string CustomerRefundAdjustmentServiceIncomeAccount { get; set; }
		public string CustomerRefundAdjustmentServiceExpenseAccount { get; set; }
		public string RemitNoteForCash { get; set; }
		public string RemitNoteForCreditCard { get; set; }
		public bool ShiftChildSchedules { get; set; }
		public int ViewInvoiceDisplayDate { get; set; }
		public int OrderConfirmationDisplayDate { get; set; }
		public string PickListNote { get; set; }
		public bool MeasurementByDecimal { get; set; }
		public string ChargeCardFeesLableInViewInvoice { get; set; }
		public bool ApplyAchFees { get; set; }
		public decimal AchFees { get; set; }
		public int ReplyToEmail { get; set; }
		public bool ShowStatusInPickList { get; set; }
		public bool ShowOrderNumberInPickList { get; set; }
		public bool ShowVendorInPickList { get; set; }
		public bool ShowProductInPickList { get; set; }
		public int ShowDescription { get; set; }
		public bool ShowStyleInPickList { get; set; }
		public bool ShowColorInPickList { get; set; }
		public bool ShowQuantityInPickList { get; set; }
		public bool ShowUOMInPickList { get; set; }
		public bool ShowPickUpLocationInPickList { get; set; }
		public bool ShowItemLocationInPickList { get; set; }
		public bool ShowMaterialOrder { get; set; }
		public bool ShowMaterialVendor { get; set; }
		public bool ShowMaterialProduct { get; set; }
		public int ShowMaterialDescrption { get; set; }
		public bool ShowMaterialStyle { get; set; }
		public bool ShowMaterialColor { get; set; }
		public bool ShowMaterialQuantity { get; set; }
		public bool ShowMaterialUOM { get; set; }
		public bool ShowMaterialPickupLocation { get; set; }
		public bool ShowLaborName { get; set; }
		public bool ShowLaborDescription { get; set; }
		public bool ShowLaborUnitCost { get; set; }
		public bool ShowLaborQuantity { get; set; }
	}
}
